SELECT  L.id,ANO_PUBLICACAO,EDICAO,EDITORA,TITULO,ID_AUTOR,ID_ASSUNTO,NOME,DESCRICAO FROM LIVRO L 
		        		 JOIN AUTOR A ON A.ID=L.ID_AUTOR  
		        	 JOIN ASSUNTO S ON S.ID =L.ID_ASSUNTO
					 order by ID_AUTOR,ID_ASSUNTO,EDICAO,ANO_PUBLICACAO,NOME
 